import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import platform from 'platform';
import Modal from '../components/modals/Modal';

const Home: NextPage = () => {

  const isMobileDevice =
  platform?.os?.family === 'iOS' || platform?.os?.family === 'Android';

  return (
    <div className=''>
      <Head>
        <title>ElrondStage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal/>
      
    </div>
  )
}

export default Home
