import type { NextPage } from 'next'
import React from 'react';
import Head from 'next/head'
import platform from 'platform';
import Modal from '../components/modals/Modal';
import FeatureHero from '../components/FeatureHero';
import TeamHero from '../components/TeamHero';
import RoadmapHero from '../components/RoadmapHero';
import MainHero from '../components/MainHero';
const Home: NextPage = () => {

  const isMobileDevice =
  platform?.os?.family === 'iOS' || platform?.os?.family === 'Android';

  return (
    <div className=''>
      <Head>
        <title>AcidPunk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal/>
      
      <main>
        <MainHero/>
        <FeatureHero/>
        <RoadmapHero/>
        <TeamHero/>
      </main>

    </div>
  )
}

export default Home
